#!/usr/bin/python

import sys

import pigpio

import time

import rospy
from std_msgs.msg import Float64


time.sleep(1)


myButton1 = 23
myButton2 = 24
myButton3 = 25
myButton4 = 12
myButton5 = 16
myLED1 = 20
myLED2 = 21
myLED3 = 26
myLED4 = 19
myLED5 = 13

PA = pigpio.pi()

PA.set_mode(myLED1,pigpio.OUTPUT)
PA.set_mode(myLED2,pigpio.OUTPUT)
PA.set_mode(myLED3,pigpio.OUTPUT)
PA.set_mode(myLED4,pigpio.OUTPUT)
PA.set_mode(myLED5,pigpio.OUTPUT)

PA.set_mode(myButton1,pigpio.INPUT)
PA.set_mode(myButton2,pigpio.INPUT)
PA.set_mode(myButton3,pigpio.INPUT)
PA.set_mode(myButton4,pigpio.INPUT)
PA.set_mode(myButton5,pigpio.INPUT)

PA.set_PWM_range(myLED1,255)
PA.set_PWM_range(myLED2,255)
PA.set_PWM_range(myLED3,255)
PA.set_PWM_range(myLED4,255)
PA.set_PWM_range(myLED5,255)

PA.set_PWM_dutycycle(myLED1,100)
time.sleep(1)
PA.write(myLED1,0)

L1=0
L2=0
L3=0
L4=0
L5=0

i = 1
while i == 1:

	print("GO")
	
	if PA.read(myButton1) == 1:
		if L1 == 0:
			PA.set_PWM_dutycycle(myLED1,100)
			L1=1
		elif L1 == 1:
			PA.write(myLED1,0)
			L1=0
		print(L1)
	
	
	if PA.read(myButton2) == 1 and PA.read(myButton3) == 0:
		if L2 == 0:
			PA.set_PWM_dutycycle(myLED2,100)
			L2=1
		elif L2 == 1:
			PA.write(myLED2,0)
			L2=0
		print(L2)
	
	
	if PA.read(myButton3) == 1 and PA.read(myButton2) == 0:
		if L3 == 0:
			PA.set_PWM_dutycycle(myLED3,100)
			L3=1
		elif L3 == 1:
			PA.write(myLED3,0)
			L3=0
		print(L3)
	
	
	if PA.read(myButton4) == 1:
		if L4 == 0:
			PA.set_PWM_dutycycle(myLED4,100)
			L4=1
		elif L4 == 1:
			PA.write(myLED4,0)
			L4=0
		print(L4)
	
	
	if PA.read(myButton5) == 1:
		if L5 == 0:
			PA.set_PWM_dutycycle(myLED5,100)
			L5=1
		elif L5 == 1:
			PA.write(myLED5,0)
			L5=0
		print(L5)





	time.sleep(0.7)
	
	if PA.read(myButton2) == 1 and PA.read(myButton3) == 1:
		i = 0

PA.write(myLED1,0)
PA.write(myLED2,0)
PA.write(myLED3,0)
PA.write(myLED4,0)
PA.write(myLED5,0)


PA.stop()

